version: '3.8'

services:
  n8n:
    build: .
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n_password
      - NODE_FUNCTION_ALLOW_EXTERNAL=pg
      - PORT=5555
      - N8N_LOG_LEVEL=info
      - N8N_METRICS=true
      - GENERIC_TIMEZONE=UTC
    ports:
      - "5555:5555"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - n8n_data:/home/node/.n8n

  postgres:
    image: postgres:16
    environment:
      - MCP_BRAVE_API_KEY=BSAKa3_9QEednD7QNH4BZ6JOt1eAq7K
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n_password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n -d n8n"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  postgres_data:
  n8n_data: